name: jt_leave_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">= 3.10.0 <4.0.0"

dependencies:
  cloud_firestore: ^6.1.2
  isar_community:
    version: ^3.3.0
  isar_community_flutter_libs:
    version: ^3.3.0
  file_picker: ^10.3.10
  firebase_admin: ^0.3.1
  firebase_auth: ^6.1.4
  firebase_core: ^4.4.0
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4
  flutter_riverpod: ^3.2.1
  intl: ^0.20.2
  open_app_file: ^4.0.4
  path_provider: ^2.1.5

dev_dependencies:
  isar_community_generator:
    version: ^3.3.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: 2.7.1

flutter:
  uses-material-design: true
  assets:
    - "lib/assets/images/jt_leave_icon_test.png"

flutter_icons:
  android: true
  ios: true
  image_path: "lib/assets/images/jt_leave_icon_test.png"
