// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'

    show defaultTargetPlatform, kIsWeb, TargetPlatform;


/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: const String.fromEnvironment('API-KEY-GENERIC'),
    appId: '1:682227031618:web:d70257a62b8b117aa457db',
    messagingSenderId: '682227031618',
    projectId: 'jtleaveimporttesting',
    authDomain: 'jtleaveimporttesting.firebaseapp.com',
    databaseURL: 'https://jtleaveimporttesting-default-rtdb.firebaseio.com',
    storageBucket: 'jtleaveimporttesting.firebasestorage.app',
    measurementId: 'G-TKDYPBD4LG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: const String.fromEnvironment('API-KEY-ANDROID'),
    appId: '1:682227031618:android:d6f501663c3606e3a457db',
    messagingSenderId: '682227031618',
    projectId: 'jtleaveimporttesting',
    databaseURL: 'https://jtleaveimporttesting-default-rtdb.firebaseio.com',
    storageBucket: 'jtleaveimporttesting.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: const String.fromEnvironment('API-KEY-GENERIC'),
    appId: '1:682227031618:ios:36272c2c4d29a914a457db',
    messagingSenderId: '682227031618',
    projectId: 'jtleaveimporttesting',
    databaseURL: 'https://jtleaveimporttesting-default-rtdb.firebaseio.com',
    storageBucket: 'jtleaveimporttesting.firebasestorage.app',
    iosBundleId: 'com.example.jtLeaveApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: const String.fromEnvironment('API-KEY-GENERIC'),
    appId: '1:682227031618:ios:36272c2c4d29a914a457db',
    messagingSenderId: '682227031618',
    projectId: 'jtleaveimporttesting',
    databaseURL: 'https://jtleaveimporttesting-default-rtdb.firebaseio.com',
    storageBucket: 'jtleaveimporttesting.firebasestorage.app',
    iosBundleId: 'com.example.jtLeaveApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: const String.fromEnvironment('API-KEY-WINDOWS'),
    appId: '1:682227031618:web:88caa77d35616bc6a457db',
    messagingSenderId: '682227031618',
    projectId: 'jtleaveimporttesting',
    authDomain: 'jtleaveimporttesting.firebaseapp.com',
    databaseURL: 'https://jtleaveimporttesting-default-rtdb.firebaseio.com',
    storageBucket: 'jtleaveimporttesting.firebasestorage.app',
    measurementId: 'G-N1MB4F2YE8',
  );
}
